version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'web_browser'
    working_dir: '/home/user/web_browser'
    tty: true
    volumes:
      - .:/home/user/web_browser
    environment:
      DISPLAY: host.docker.internal:0.0
